language: python
python:
  - "3.9"

services:
  - postgresql

before_script:
  - - psql -c 'create database travis_ci_test;' -U postgres
  - pip install pipenv
  - pipenv install --dev
  - python manage.py migrate

script:
  - python manage.py test
